export const CARD_LIST_REQUEST = 'CARD_LIST_REQUEST';
export const CARD_LIST_SUCCESS = 'CARD_LIST_SUCCESS';
export const CARD_LIST_FAIL = 'CARD_LIST_FAIL';

export const CARD_DETAILS_REQUEST = 'CARD_DETAILS_REQUEST';
export const CARD_DETAILS_SUCCESS = 'CARD_DETAILS_SUCCESS';
export const CARD_DETAILS_FAIL = 'CARD_DETAILS_FAIL';


export const FOOTER_LIST_REQUEST = 'FOOTER_LIST_REQUEST';
export const FOOTER_LIST_SUCCESS = 'FOOTER_LIST_SUCCESS';
export const FOOTER_LIST_FAIL = 'FOOTER_LIST_FAIL';


export const SIDEBAR_LIST_REQUEST = 'SIDEBAR_LIST_REQUEST';
export const SIDEBAR_LIST_SUCCESS = 'SIDEBAR_LIST_SUCCESS';
export const SIDEBAR_LIST_FAIL = 'SIDEBAR_LIST_FAIL';