// Generated by https://quicktype.io

import {
  BgSVG,
  InvestmentInfo,
  ResponseInfo,
  ReturnInfo,
} from "./HomeInterface";

export interface Apikitpage {
  title: null;
  section_data: SectionDatum[];
  api_kits_cards: APIKitsCard[];
}

export interface APIKitsCard {
  title: string;
  subTitle: string;
  cardTag: string;
  subTag: string;
  desc: string;
  filterTag: string;
  avatar: BgSVG[];
  descImg: BgSVG;
  bgSvg: BgSVG;
  topRightCornerImg: BgSVG;
  points: Point[];
  api_info: APIInfo;
  investment_info: InvestmentInfo;
  rating_info: RatingInfo;
  return_info: ReturnInfo;
  response_info: ResponseInfo;
  success_info: SuccessInfo;
  links: Link[];
}

export interface APIInfo {
  title: string;
  tag: string;
  titleTag: string;
  api: number;
  apiCallsAvg: number;
  icon: BgSVG;
}

export interface Link {
  title: string;
  href: null;
  icon: null;
}

export interface Point {
  title: string;
  tag: null | string;
  sortDesc: null;
  bg: null;
  bgSvg: null;
  icon: BgSVG;
  descImg: Url;
}
export interface Url {
  url: string;
}

export interface RatingInfo {
  title: string;
  tag: string;
  ratingTag: string;
  ratingCount: string;
  rating: string;
  icon: BgSVG;
}

export interface SuccessInfo {
  title: string;
  tag: string;
  successRate: number;
  icon: BgSVG;
}

export interface SectionDatum {
  title: string;
  api_kits_cards: APIKitsCard[];
}
